# Generated by Django 5.0.6 on 2024-07-08 21:43

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512, null=True)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
    ]
